[package]
name = "mdbook-latex-pdf"
version = "0.1.0"
edition = "2021"

[features]
default = ["latex", "pdf"]
latex = []
pdf = ["latex", "tectonic", "tectonic_bridge_core"]

[dependencies]
anyhow = "1.0.57"
mdbook = "0.4.18"
pulldown-cmark = "0.9.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_derive = "1.0.137"
tectonic = { version = "0.9.0", optional = true }
tectonic_bridge_core = { version = "0.3.0", optional = true }
regex = "1.5.5"
clap = "3.1.18"
walkdir = "2.3.2"
resvg = "0.22.0"
Inflector = "0.11.4"
usvg = "0.22.0"
tiny-skia = "0.6.3"
serde_json = "1.0.81"
structopt = "0.3.26"
html5ever = "0.26.0"
markup5ever = "0.11.0"
tendril = "0.4.3"
